# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VeracodeCli < Formula
  desc "You use the Veracode CLI to perform various actions for testing the security of your applications."
  homepage "https://www.veracode.com"
  version "2.14.0"
  license "MIT"

  on_macos do
    url "https://tools.veracode.com/veracode-cli/veracode-cli_2.14.0_macosx_arm64.tar.gz"
    sha256 "99a9d334355606e2b5b204f06cd770e1a93b34091736fde7639309eeb34485b2"

    def install
      bin.install "veracode"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.14.0_linux_x86.tar.gz"
      sha256 "8ae69677068356a816d8f0a9ea884ccabdc3cf268f548641a38e477ee541f812"

      def install
        bin.install "veracode"
      end
    end
    if Hardware::CPU.intel?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.14.0_linux_x86.tar.gz"
      sha256 "8a8de70e02cecdc1e96392a8882e4a99a256cf547703ca9a33855a4d506fd924"

      def install
        bin.install "veracode"
      end
    end
  end

  test do
    system "#{bin}/veracode --version"
  end
end
